"""empty message

Revision ID: d9525c3047c1
Revises: 
Create Date: 2023-10-28 18:43:43.213283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd9525c3047c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('untitled_table_312')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('untitled_table_312',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('unique_rowid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='untitled_table_312_pkey'),
    comment='Calculates square of the correlation coefficient.'
    )
    # ### end Alembic commands ###
